USE my1;

-- Tạo bảng BOOK
CREATE TABLE BOOK (
    MaSach CHAR(5) PRIMARY KEY,  
    TenSach VARCHAR(200) NOT NULL,  
    SoLuong INT NOT NULL,
    GiaThue DECIMAL(10,2) NOT NULL DEFAULT 5000,
    NgayNhap DATE, 
    CONSTRAINT CK_SoLuong CHECK (SoLuong >= 0) 
);

-- Tạo bảng BORROW_BOOKS
CREATE TABLE BORROW_BOOKS (
    MaMuon INT PRIMARY KEY AUTO_INCREMENT, 
    MaSach CHAR(5) NOT NULL,
    NgayMuon DATE NOT NULL DEFAULT (CURRENT_DATE),
    CONSTRAINT FK_Book FOREIGN KEY (MaSach) REFERENCES BOOK(MaSach)
);
